version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: ${APP_IMAGE_NAME}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_EXTERNAL_PORT}:${APP_INTERNAL_PORT}
    env_file:
      - ./prod.env
